'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, Download, FileText, Loader2, RefreshCw } from 'lucide-react';

import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Skeleton from '@/components/ui/Skeleton';
import MemoContent from '@/components/deals/MemoContent';
import { getMemoByDealId, generateMemo } from '@/services/memoService';
import { getDueDiligenceByDealId } from '@/services/dueDiligenceService';
import type { Deal, Finding, ICMemo } from '@/types';
import { formatDateTime } from '@/lib/utils';

interface ICMemoTabProps {
  deal: Deal;
}

export default function ICMemoTab({ deal }: ICMemoTabProps) {
  const [memo, setMemo] = useState<ICMemo | null>(null);
  const [findings, setFindings] = useState<Finding[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([getMemoByDealId(deal.id), getDueDiligenceByDealId(deal.id)]).then(
      ([memoData, dueDiligenceData]) => {
        setMemo(memoData ?? null);
        setFindings(dueDiligenceData?.findings ?? []);
        setIsLoading(false);
      }
    );
  }, [deal.id]);

  async function handleGenerate() {
    setIsGenerating(true);
    setError(null);

    try {
      const newMemo = await generateMemo(deal.id);
      setMemo(newMemo);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate IC memo. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  }

  if (isLoading) {
    return (
      <Card>
        <Skeleton className='mb-6 h-6 w-64' />
        <div className='space-y-3'>
          <Skeleton className='h-4 w-full' />
          <Skeleton className='h-4 w-full' />
          <Skeleton className='h-4 w-5/6' />
          <Skeleton className='h-4 w-full' />
          <Skeleton className='h-4 w-2/3' />
        </div>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className='flex flex-col items-center gap-3 py-16 text-center'>
        <AlertTriangle className='h-8 w-8 text-red-400' />
        <p className='text-sm font-medium text-slate-700'>{error}</p>
        <Button onClick={handleGenerate} loading={isGenerating}>
          Try Again
        </Button>
      </Card>
    );
  }

  if (!memo && isGenerating) {
    return (
      <Card className='flex flex-col items-center gap-2 py-20 text-center'>
        <Loader2 className='h-8 w-8 animate-spin text-indigo-500' />
        <p className='text-sm font-medium text-slate-700'>Generating memo from deal data...</p>
        <p className='text-xs text-slate-400'>This can take up to 30 seconds.</p>
      </Card>
    );
  }

  if (!memo) {
    return (
      <Card className='flex flex-col items-center gap-3 py-20 text-center'>
        <FileText className='h-8 w-8 text-slate-300' />
        <p className='text-sm font-medium text-slate-900'>No IC Memo Generated</p>
        <p className='max-w-md text-sm text-slate-500'>
          Generate an Investment Committee memo based on deal data, securities, and diligence findings.
        </p>
        <Button size='lg' onClick={handleGenerate} loading={isGenerating} className='mt-2'>
          Generate IC Memo
        </Button>
      </Card>
    );
  }

  return (
    <div className='space-y-6'>
      <div className='flex flex-wrap items-center justify-between gap-3'>
        <div>
          <h2 className='text-lg font-semibold text-slate-900'>Investment Committee Memo</h2>
          <p className='mt-0.5 text-xs text-slate-500'>Generated on {formatDateTime(memo.generatedAt)}</p>
        </div>
        <div className='flex items-center gap-2'>
          <Button variant='ghost' size='sm'>
            <Download className='h-3.5 w-3.5' />
            Export to PDF
          </Button>
          <Button variant='secondary' size='sm' onClick={handleGenerate} loading={isGenerating}>
            <RefreshCw className='h-3.5 w-3.5' />
            Regenerate
          </Button>
        </div>
      </div>

      <MemoContent content={memo.content} findings={findings} />

      {memo.provider && memo.model && (
        <p className='text-center text-xs text-slate-400'>
          Generated by {memo.provider} · {memo.model}
        </p>
      )}
    </div>
  );
}
